name: AWS resource creation using terraform
 
on:
  push:
    branches:
      - master
    paths:
      - 'Jenkinsserver/**'
  workflow_dispatch:
    inputs:
      tfvars_file:
        description: 'Path to the .tfvars file'
        required: true
        default: 'variable.tfvars'
      action:
        type: choice
        description: 'Choose action: plan, apply, or destroy'
        options:
          - plan
          - apply
          - destroy
        required: true
        default: 'apply'

env:
  AWS_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

permissions:
  contents: read

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.8.4

  init:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Terraform Init
        working-directory: Jenkinsserver
        run: terraform init

  validate_format:
    runs-on: ubuntu-latest
    needs: init
    steps:
      - name: Terraform Format
        working-directory: Jenkinsserver
        run: terraform fmt

      - name: Terraform Validate
        working-directory: Jenkinsserver
        run: terraform validate

  terraform_action:
    runs-on: ubuntu-latest
    needs: validate_format
    steps:
      - name: Terraform Plan
        if: ${{ github.event.inputs.action == 'plan' }}
        working-directory: Jenkinsserver
        run: terraform plan -var-file=${{ github.event.inputs.tfvars_file }} -input=false

      - name: Terraform Apply
        if: ${{ github.event.inputs.action == 'apply' }}
        working-directory: Jenkinsserver
        run: terraform apply -auto-approve -var-file=${{ github.event.inputs.tfvars_file }} -input=false

      - name: Terraform Destroy
        if: ${{ github.event.inputs.action == 'destroy' }}
        working-directory: Jenkinsserver
        run: terraform destroy -auto-approve -var-file=${{ github.event.inputs.tfvars_file }} -input=false
